[package]
name = "my_ast_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rstest = "0.11.0"


[dependencies]
nom = "7.1.0"

